name: Rust

on:
  push:
    branches: [ main ]
    tags:        
      - "*"
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: "1.59.0"
        override: true
        default: true
    - name: Build
      run: cargo build --release && strip target/release/log-converter
    - name: Run tests
      run: cargo test
    - name: Run integration tests
      run: ./test
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/log-converter
